// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Extensions.V1Beta1
{

    [OutputType]
    public sealed class IngressBackend
    {
        /// <summary>
        /// Specifies the name of the referenced service.
        /// </summary>
        public readonly string ServiceName;
        /// <summary>
        /// Specifies the port of the referenced service.
        /// </summary>
        public readonly Union<int, string> ServicePort;

        [OutputConstructor]
        private IngressBackend(
            string serviceName,

            Union<int, string> servicePort)
        {
            ServiceName = serviceName;
            ServicePort = servicePort;
        }
    }
}
