// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Extensions.V1Beta1
{

    /// <summary>
    /// HTTPIngressPath associates a path regex with a backend. Incoming urls matching the path are forwarded to the backend.
    /// </summary>
    public class HTTPIngressPathArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Backend defines the referenced service endpoint to which the traffic will be forwarded to.
        /// </summary>
        [Input("backend", required: true)]
        public Input<Pulumi.Kubernetes.Types.Inputs.Extensions.V1Beta1.IngressBackendArgs> Backend { get; set; } = null!;

        /// <summary>
        /// Path is an extended POSIX regex as defined by IEEE Std 1003.1, (i.e this follows the egrep/unix syntax, not the perl syntax) matched against the path of an incoming request. Currently it can contain characters disallowed from the conventional "path" part of a URL as defined by RFC 3986. Paths must begin with a '/'. If unspecified, the path defaults to a catch all sending traffic to the backend.
        /// </summary>
        [Input("path")]
        public Input<string>? Path { get; set; }

        public HTTPIngressPathArgs()
        {
        }
    }
}
